### ISSUE TITLE
Error running with nginx-proxy

### ISSUE THREAD

**Issue by pavelsr** [o1lab/xmysql#20]
Hello, @o1lab,

I'm running  xmysql from your container `markuman/xmysql` and want to use it with [nginx-proxy](https://github.com/jwilder/nginx-proxy) container together.

```bash
	docker run -d \
	-e VIRTUAL_HOST=api.example.com \
        -e VIRTUAL_PORT=3000 \
	-e DATABASE_HOST=example-blog-db-mysql \
	-e DATABASE_USER=root \
	-e DATABASE_PASSWORD=fab14france \
	-e DATABASE_NAME=wordpress \
	--name xmysql --restart=always \
	--network nginx-proxy \
	markuman/xmysql
````

`docker logs xmysql ` said that xmysql started fine:

```



          Generating REST APIs at the speed of your thought.. 

 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
                                                            
          Database              :    wordpress
          Number of Tables      :    12
                                                            
          REST APIs Generated   :    228
                                                            
          Xmysql took           :    1.1 seconds
                                                            
 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
```

But when I go to api.example.com I see `502 Bad Gateway` nginx error.

nginx log of the request:

```
connect() failed (111: Connection refused) while connecting to upstream, client: 178.76.224.96, server: api.example.com, request: "GET / HTTP/1.1", upstream: "http://172.19.0.13:3000/", host: "api.example.com"
```

Strings from generated default.conf of nginx-proxy:

```
upstream api.example.com {
			server 172.19.0.13:3000;
}
...
server {
	server_name api.example.com;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	include /etc/nginx/vhost.d/default;
	location / {
		proxy_pass http://api.example.com
	}
}
```

Please help me find out what could be the issue.
IP address of xmysql docker container is correct.

```
# docker exec -it xmysql /bin/sh
/usr/src/app # node -v
v8.9.3
/usr/src/app # npm -v
5.5.1
/usr/src/app # mysql --version
/bin/sh: mysql: not found
/usr/src/app # xmysql --version
/bin/sh: xmysql: not found
```

**Comment by o1lab** [comment]
@markuman : Can you please take a look at this.

**Comment by o1lab** [comment]
This [stackoverflow](https://serverfault.com/questions/317393/connect-failed-111-connection-refused-while-connecting-to-upstream) question might be of help.

**Comment by markuman** [comment]
I've updated the docker image (dockerfile) but haven't pushed it yet.
But let me look into this

**Comment by markuman** [comment]
> ```
> 	-e VIRTUAL_HOST=api.example.com \
> 	-e VIRTUAL_PORT=3000 \
> ```

The xmysql Dockerfile don't know this environment variables.

But nevermind, the `docker log xmysql` output looks good. The fact that it doesn't response is that I apply new version of xmysql without update the `docker-entrypoint.sh` file. xmysql is only listen on localhost by default, so it will run inside the docker container and did nothing.



```diff
diff --git a/docker-entrypoint.sh b/docker-entrypoint.sh
index 84a52ca..7c00d20 100755
--- a/docker-entrypoint.sh
+++ b/docker-entrypoint.sh
@@ -1,3 +1,3 @@
 #!/bin/sh
 cd /usr/src/app/
-node index.js -h $DATABASE_HOST -p $DATABASE_PASSWORD -d $DATABASE_NAME -u $DATABASE_USER
\ No newline at end of file
+node index.js -h $DATABASE_HOST -p $DATABASE_PASSWORD -d $DATABASE_NAME -u $DATABASE_USER -n 80 -r 0.0.0.0
```



The image is already pushed, so you just need to pull and it sould be run. But take care, I've changed the local docker port to 80. So you need to publish `-p 3000:80`.  The benefit is, that you can address xmysql in your other services just with `http://xmysql` , that's it.

So yes, point taken. we need docker versions which follows xmysql versions. I'll prepare a new merge request with all changes and documentation update.



# Here is an minimal example with nginx proxy

## 1st create nginx.conf

there is no need for upstream the xmysql host.  
when you need load balancing, just use `docker swarm mode` and `docker service create --name xmysql --replicas 10 ...`

```shell
echo '
events {
   worker_connections 1024;
   
}
http {
    server {
        server_name api.example.com 127.0.0.1;
        listen 80 ;
        location / {
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass http://xmysql;
        }
    }
}
' > /tmp/nginx.conf
```

## 2nd create a docker network

make sure you've created a docker network

`docker network create local_dev`

## 3rd deploy xmysql

use `local_dev` network, so other container can reached xmysql by it's name `xmysql` (the `--name` value). no need to use ip address in other containers.  
we published port 3000 on host system for debugging. internaly the image use now port 80, because then you can easily use `wget http://xmysql/`

```shell
docker run -d \
--network local_dev
--name xmysql
--p 3000:80
-e DATABASE_HOST=example-blog-db-mysql \
-e DATABASE_USER=root \
-e DATABASE_PASSWORD=fab14france \
-e DATABASE_NAME=wordpress \
markuman/xmysql
```

now check you browser on `127.0.0.1:3000`. When not, deploying nginx will fail because the upstream host is not reachable.

## 4th deploy nginx

```shell
docker run -d \
--network local_dev \
--name nginx \
-p 80:80 \
-v /tmp/nginx.conf:/etc/nginx/nginx.conf \
nginx:alpine
```

**Comment by o1lab** [comment]
@markuman : well made instructions mate  :clap: :raised_hands:

**Comment by o1lab** [comment]
@pavelsr : I hope @markuman 's changes should help resolve with nginx-proxy now. I'll be closing this issue eod. Feel free to reopen if needed.

@markuman - capturing details above of configuring nginx proxy would be useful in documentation ? Could you please help make a pull request to Readme.md. Thank you.
