### ISSUE TITLE
Where is it installed if i wanted to make changes in the API

### ISSUE THREAD

**Issue by ryhill** [o1lab/xmysql#25]
Where are the files installed on the server  if i wanted to make changes in the API

**Comment by o1lab** [comment]
If I am not wrong - I understand the question as programmatic use of Xmysql where one can have methods to override or have hooks before/after for each API. This is something which is being considered in the future releases.

**Comment by clancye** [comment]
@o1lab I've been thinking about this because I want to perform some backend input validation on the fields before xmysql includes them in a query. Did you have a potential implementation for the hooks? Would we have to write these in a separate JS file to be referenced by xmysql?

One possible workaround that doesn't involve any xmysql development is to have two backend layers: validation and xmysql. Validation layer receives HTTP requests from front end, checks the input data against certain business rules to make sure it will be a valid query, and then sends the request to the xmysql server to execute the query.

Another solution would be to make xmysql a library we can use inside our own Node app to generate an instance of a xmysql class and use its methods. This would allow the backend server to receive a request from the frontend, run some checks on the input fields according to business rules, and then call some xmysql methods to alter the database. This would simplify the backend architecture in comparison to my other suggestion. Here's the general idea:

```
const app = require('express')  
const xmysql = require('xmysql')

xmysql.initialize(host, user, dbname)

app.post('/table_name', (req, res) =>{
  if(postPrecheck(table_name, req, res) === false){
    res.send(500)
  } else {
    xmysql.xctrl.create(req)
    res.send(200)
  }
})
```

postPrecheck() would be filled out by the user. It's a work in progress, but wanted to share my thoughts.

**Comment by o1lab** [comment]
@clancye please refer to auth issue which is open. Im addressing it there in future.

**Comment by karelnet** [comment]
> 
> 
> If I am not wrong - I understand the question as programmatic use of Xmysql where one can have methods to override or have hooks before/after for each API. This is something which is being considered in the future releases.

I understand this : 
Is xmysql generating some code (e.g. expressjs files) for the api that we could get somewhere and manually change for using on another expressjs. xmysql would be used as an api "generator" for express.

**Comment by o1lab** [comment]
>> Is xmysql generating some code (e.g. expressjs files) for the api that we could get somewhere and manually change for using on another expressjs

Currently, xmysql is not generating code in any files. Its all within data structures in memory.

@clancye : sorry I could not come back other day completely as I was on mobile. I am reconsidering some aspect to give hooks given how easy it is now to just run xmysql as docker.

Having apis in files makes it easy to develop on.
Having hooks will make it easy to say from docker point of view.

I would be happy to keep both if possible. Any suggestions from docker point of view and hooks are welcome.

**Comment by BaseD75** [comment]
Regarding the comment of @karelnet and @o1lab his answer:
I was looking on the net for a way to generate API code given some mySQL tables and found this project (which is great by the way :-). 

But now I do not quite understand the answer. Will there (maybe) be a feature in te future to only generate code instead of immediately running the express server so I can use it as a starting point for further developement? Or maybe there is already something else that makes this possible?
